name: user-authentication

services:
  db:
    image: postgres:18-alpine
    container_name: user-authentication
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user-authentication
    ports:
      - "5432:5432"
    volumes:
      - user-authentication-data:/var/lib/postgresql

volumes:
  user-authentication-data:
